### ISSUE TITLE
summary reference

### ISSUE THREAD

**Issue by ZhangShiyue** [artidoro/frank#2]
Hi, 

Thanks for your awesome work!

I just wonder if you would consider include summary references in your benchmark data. Because probably people want to test their general summarization metrics on your benchmark too. 

Shiyue

**Comment by artidoro** [comment]
Hey @ZhangShiyue, that's a great point! I have been thinking about article-based metrics, but I will add the reference summaries as well to allow testing reference-based metrics.

I'll let you know when that's done.

**Comment by artidoro** [comment]
@ZhangShiyue  I just added reference summaries to the benchmark data file. Let me know if you have any other suggestions!

**Comment by ZhangShiyue** [comment]
Great! Thanks!
