### ISSUE TITLE
BERTscore implementation

### ISSUE THREAD

**Issue by Lukecn1** [artidoro/frank#3]
Hi Artidoro, 

Can you provide the details on the BERTscore implementation you have used to derive the scores in the data? 

I am having difficulty replicating them exactly.

**Comment by artidoro** [comment]
Hello, I just verified and the results in the baseline_factuality_metrics_outputs.json are incorrect.
I apologize for the issue and will update the file and upload the latest results to the website.

Thank you very much for reporting the problem!

**Comment by Lukecn1** [comment]
I just reran my scores and all looks good now, thanks for the quick update :)
